YOURLS/awesome

README.md
Defines optional conditions under which links will expire, able to set time and click limited links globally or per individual links.
=> Added: Expiry

README.md
Hello,
I updated README.md file, because i changed old translation for Turkish(link has been changed in file). It was not correct %100.
Could you please check and approve it.
Thanks in advance.
=> Update README.md for better Turkish Translation. (link changed)

README.md
Hello! I replaced the Italian translation link, as it is pointing to a Google Code project that is currently broken. Hope my edit is fine :)
Thanks!
=> Updated Italian translation link

README.md
Removed a duplicate entry for "Advanced Reserved URLs"
=> Removed a duplicate entry

README.md
When I saved the file a few line endings within the file have been changed as well.
=> add plugin: JSON Response

README.md
Plugin Source:
- https://github.com/guessi/yourls-dont-log-health-checker
=> New Plugin: Added ability to filter out traffic from health checker(s)

README.md
Translated YOURLS language into Telugu, added a link in README markdown.
see the translation [here](https://github.com/kalyan4786/YOURLS_Telugu_Translation)
=> Added Telugu Translation for YOURLS

README.md
I recently decided to change my username, this pull request reflects the change.
=> Fixed plugin URL

README.md
The YOURLS module listed for Drupal is outdated and limited in functionality. There is an alternate solution with another Drupal module which requires a bit of legwork. Alternate module and appropriate issue in Drupal linked for reference.
=> Added alternate Drupal module

README.md
This plugin makes the username lowercase when logging in.
=> New plugin: Make username lowercase

README.md
This API plugin checks for 301/302 redirects at the destination points, and updates the YOURLS database accordingly. Handy for things like a Drupal to Wordpress migration. Will also return number of attempts, failures, and dead links along with an array of dead links.
=> Add: Update-30X

README.md
Adds a link to https://github.com/HeroCC/yourls-conditional-urlads, my YOURLS plugin that redirects links through various advert pages
=> Add Conditional URL Advertisements

README.md
The Admin Issue Diagnostic - A.I.D. Plugin collects YOURLS environmentals and formats a template to copy/paste into a YOURLS issue. Just fill in the blanks! Fantastic for newbies, great for experts!
=> Adds the Admin Issue Diagnostic - A.I.D. Plugin

README.md
Add Time-Period Clicks plugin.
=> Time-Period Clicks

README.md
Removed inactive links under translations section
=> Removed deleted translations

README.md
I've created a Plugin for YOURLS that enables the sharing through Telegram Messenger.
A License is included at [source](https://git.neht.xyz/ColinShark/yourls_tg-quickshare).
=> Added Telegram Quickshare plugin

README.md
Added a plugin for per-IP lockout functionality when a certain number of failed logins is reached.
=> Add login timeout plugin

README.md
- If a submitted URL does not meet [RFC 2396](http://www.faqs.org/rfcs/rfc2396.html) standards, it is rejected
- If a submitted http(s) URL is unreachable (times out after 3 seconds), it is rejected
- If a submitted http(s) URL is a redirect, the final destination is stored to avoid nested redirects
=> Add URL Health Check

README.md
Also added Mac category. Closes #38
=> Add Short Menu to the list of YOURLS Applications

README.md
=> Update Mac pricing for Short Menu

README.md
Added a laravel plugin to the list of 3rd party tools available
=> Added Laravel to the list

README.md
Hello!
I would like to propose my simple plugin that allows you to change the image of the YOURLS logo and its alt and title tags.
=> YOURLS GWall Change Logo

README.md
`:)`
https://discourse.yourls.org/t/a-new-python-3-wrapper-library
=> Added Pyourls3

README.md
Which makes me notice there was already a plugin for this ... :roll_eyes:
=> Add change password

README.md
I wrote this plugin (OAuth_Sign_In) about 3 weeks ago, with some tutorials including using this plugin and building service with docker.
=> Add OAuth_Sign_In

README.md
Updated Readme file with new android app and frontend and backend theme called Sleeky
=> Added android app and Sleeky theme

README.md
=> New Android app

README.md
Updated app store URL for ShortFox
=> Updated ShortFox iOS App.

README.md
G'day,
Added a plugin for AAF Rapid Connect authentication.
Also cleaned up a whitespace issue.
Regards,
Christopher
=> Added AAF Rapid Connect authentication

README.md
SMTP contact provides a public contact page and uses PHPMailer to deliver mail.
=> Adding SMTP contact

README.md
Simple new Android app, removed non-existing link from other app
=> Add iC-YOURLS (Android)

README.md
I made a complete german translation for the new YOURLS 1.8 .
=> Update README.md – german translation

README.md
Hey. I know that there's already a telegram bot listed, but this one is open source and more specialized on YOURLS, so here I am PRing :)
=> Add yourls-bot to 3rd party integrations

README.md
similar to y.at logic, but for your own YOURLs instance
=> Add @telepathics emoji plugin

README.md
=> Replace zh_TW translation link to one that is maintained

README.md
=> Remove @matbra's Multi User

README.md
I want to add the `Change Title` plugin
=> Add Change Title plugin

README.md
Hello!
I've been created a catalan translation for YOURLS.
Here my pull request with the link to the repo.
Cheers!
=> Catalan translation added

README.md
ozh recommended I add this and make a PR.
=> Added my Users in Database plugin gist.

README.md
Added [2fa-support plugin](https://github.com/MatthewC/yourls-2fa-support)
=> Added 2fa-support

README.md
=> Added Added Fancy Pokemon URLs plugin

README.md
yourls-authmgr-plugin is deprecated
=> yourls-authmgr-plugin is deprecated

README.md
update translation from [1.7.3](https://github.com/ZvonimirSun/YOURLS-zh_CN) to [1.9.1](https://github.com/taozhiyu/yourls-translation-zh_CN)
=> Update zh_CN to 1.9.1

README.md
=> Add Telegram Notifier

README.md
Ref: https://github.com/YOURLS/website/issues/107
=> Fix Conditional Toolbar plugin link

README.md
👋 just sharing my custom guide to install in Windows
=> add guide to install in wamp

README.md
add query-string-keeper plugin,tested on YOURLS version 1.8.3 and php version 8.0.12.
=> Add query-string-keeper plugin 

README.md
This code differs from the previous version as it provides more information and utilizes a different configuration path.  If the path does not exist, it will be created the first time the command is executed.
=> add: bash script from masdzub

README.md
I created this quickly for YOURLS/YOURLS#3819, but it's not exactly the first time this question (how to have shorturls whose destinations change frequently work better) has come up.
=> Add Caching Disabled for Redirects plugin

README.md
Thanks for the _awesome_ repo! :)
=> Adds Random Redirect Manager & Awin Affiliate plugins

README.md
=> Point to newest known fork of SQLite DB driver

README.md
Add a plugin: Referer Restrict. One installation tutorial lost, one installation tutorial added，在宝塔面板安装一个很受欢迎的短链接网站开源程序YOURLS
=> Add plugin and Chinese tutorials
