YOURLS/awesome

README.md
Hi everyone,
I've noticed both **Admin NoCaptcha** and **Admin reCaptcha** entries point to the same repository: https://github.com/armujahid/Admin-reCaptcha
So I put the correct name and link to the "No CAPTCHA reCAPTCHA" plugin as follows:
>**Admin NoReCAPTCHA**: https://github.com/amindeed/YOURLS-Admin-NoReCAPTCHA
*instead of:*
>**Admin NoCaptcha**: https://github.com/armujahid/Admin-reCaptcha
=> Corrected the link to No CAPTCHA reCAPTCHA plugin

README.md
There's an mobile device Apps promotion links
- iOS users would be redirected to Apple Store
- Android users would be redirected to Google Play Store
- Other users would be redirected to product promotion page
User who wants to view http(s)://yourls.domain/XYZ
* iOS users will be redirected to http(s)://yourls.domain/iosXYZ
* Android users will be redirect to: http(s)://yourls.domain/androidosXYZ
* For the rest of others, will be rediected to: http(s)://yourls.domain/XYZ
if it is failed to search iosXYZ or androidosXYZ, return "not found"
implementation required additional keyword with pre-defined prefix:
- iosXXXX
- androidosXXXX
the prefix comes from upstream "[Mobile-Detect](https://github.com/serbanghita/Mobile-Detect)" project
- …
=> New Plugin: Added ability to redirct by detecting device type

README.md
It was a 404, so I changed to the GitHub source.
=> Wrong link for Popular Links plugin

README.md
I removed the outdated links, and improved the formatting of the apps listed under 'Other devices and softwares', and fixed the issue with the markdown not being properly formatted for the URLs.
All of the apps listed under the Mac category were no longer available (or at least I couldn't find the download link), and most of the apps under the iOS category were removed from the App Store, except for one which does not work on the latest version of iOS. I also added my app (ShortFox) to the list under iOS. The chrome extension linked no longer existed, but I found a replacement on the chrome web store.
=> Removed outdated links, and improved formatting

README.md
This plugin merges @nicwaller's authmgr and @ianbarber's Seperate-Users plugins with (sometimes up to 5 years worth of) bug squashing, heavy code revisioning, and feature enhancement. Robust with hooks to filter data, this will integrate nicely with other plugins. I envision this as a great starting point for native user management. See the commit histories of my forks of the two plugins for a complete list of updates and enhancements.
=> Add Auth Manager Plus

README.md
This YOURLS plugin enables the possibility to have different redirection URLs depending on the country of the visitor, by using YOURLS GeoIP plugin or by using the web server's built-in GeoIP module.
PR Motivated by [this issue](https://github.com/YOURLS/YOURLS/issues/2426)
=> Adding GeoShortURL plugin

README.md
No WP plugins seem to have support for displaying YOURLS short URLs in a widget on the post page. This solution fills that gap and provides optional QR code display.
=> Link to YOURLS Wordpress Widget gist

README.md
The new one is for v1.7 and the old one is still based on v1.6.
=> Update zh_CN translation

README.md
Adding 2 plugins. 1 enables OIDC authentication, the other stops admin tracking and is compatible with the OIDC plugin.
=> adding OpenID Connect

README.md
I've moved the plugin from my selfhosted Gitea instance to Github and updated the Link accordingly.
=> Edit link to Telegram Quickshare repository

README.md
The SEODENVER site is no longer active, but Zack Katz has a great link tracking plugin that works really well.
=> Update link for Google Analytics Link Tracking

README.md
- problem: YouTube titles are not reliably returned to YOURLS ([case use example](https://github.com/joshp23/YOURLS-title-refetch/issues/11))
- solution: fetch YouTube titles via Google API with this simple plugin
=> Add YouTube Title Fix

README.md
Adding «Lookup keywords by long URL substring»: a plugin for YOURLS designed to lookup all keywords which resolve to URLs containing specified substring.
Plugin URL: https://github.com/bryzgaloff/yourls-api-lookup-keywords-by-url-substr
=> lookup-url-substr: API action for searching by long URL substring

README.md
This adds an actively maintained version of the SQLite driver.
I've kept the original version, in case anyone wishes to use it with an older YOURLS installation, as this version is not backwards compatible.
=> Add actively maintained SQLite driver for YOURLS.

README.md
A [Gnome](https://www.gnome.org/) desktop extension enabling url shortening from the clipboard.
=> add Gnome Shell Extension

README.md
Inject a (customizable) landing page checkpoint to let visitors know when they are about to hit a referral link.
=> Add @telepathics referral checkpoint plugin

README.md
Send a notification to a Slack channel whenever a new short URL is created.
=> Add a new plugin, Slack Notifier

README.md
adds link to Getting Started video that includes Automator/Keyboard Maestro shortcuts for replacing URLs in text on macOS.
=> add tutorial video

README.md
Only supports Discord notification and when a new link is added for now.
=> Add Notifier plugin

README.md
This plugin makes the exact opposite of the limit keyword length plugin from adigitalife
=> Add another limit keyword length plugin

README.md
It adds a link to the YOURLS Prometheus exporter. It allows people to monitor their YOURLS instances with Prometheus.
I also reserved a port on the [Official list of Exporter ports](https://github.com/prometheus/prometheus/wiki/Default-port-allocations).
More information about Prometheus exporters : https://prometheus.io/docs/instrumenting/exporters/
=> Add new integration: Prometheus exporter

README.md
Added 'Fancy Animals Short Urls' to the README.md. I believe it's in the correct alphabetical order. It's a fork/modification of Ozh's Word Based Short Url modified to use three word lists Adjective, Color, Animal to create URL's like https://short.rip/SwiftCrimsonBullfrog
=> Added 'Fancy Animals Short Urls' to the README.md

README.md
`u.nu` no longer uses YOURLS, and we changed our public YOURLS service domain to `your.ls` now
=> Add your.ls

README.md
Because there are some spam browsers in China that block shorting-URL, this is a special event to get this plugin
https://github.com/8Mi-Tech/yourls-ban-useragent
=> Upload Plugin : Blacklist User-Agent

README.md
Hey guys, it would be cool to see my plugin propagating to your awesome list of awesome plugins!
=> Added "BaseURL Rewrite" plugin to list of plugins

README.md
Yet another query string forwarding plugin. What sets this one apart is the ability to exclude query params by host (regex supported)
=> Add Query String Forwarder Plugin

README.md
This plugin allows you to replace tokens or the entire URL based on regex, scripts, or simple text replacement. 
https://github.com/takuy/yourls-replacetext
=> New Plugin: Replace Text

README.md
Limit Custom Keyword Length (Min & Max Characters) - This plugin limits the minimum and maximum number of characters for custom keyword.
=> Add New Plugin: Limit Custom Keyword Length (Min & Max Characters)

README.md
Added 2 of my plugins,
Support for Cloudflare Turnstile on the login page and plugin to purge all logs for the people too lazy to delete them from the database :)
=> Add Admin Turnstile & Purge All Logs plugins

README.md
Adds API Iist Extended plugin to readme.md file: https://github.com/Codeinwp/yourls-api-list-extended
=> Add "API List Extended" plugin

README.md
=> Add Better Blacklist Domains plugin + updated Bash script

README.md
Add a new plugin - Broken Banisher
Also, remove an extra space
=> Add Broken Banisher plugin to the list

README.md
This plugin enables the addition of a **custom header to the URL**, facilitating compliance with regulatory requirements in certain countries, such as India, for bulk SMS services. Pass `custom_header` in query param to add custom header as prefix to the generated short url
=> added plugin YOURLS-Custom-Header name

README.md
This is for generating qr codes for short urls using Quickchart. Allows using a self hosted Quickchart instance, defaulting to the main instance.
=> Add in QRCode Quickchart

README.md
A simple plugin to redirect based on User-Agent, all blacklisted user agents won't be redirected to target URL but instead shown a custom page.
=> Add Redirect based on User-Agent
